ALTER TABLE ROLExENGINEER ADD
	CONSTRAINT FK_ROLExENGINEER_ROLE_ID_Role
	FOREIGN KEY (ID_Role)
	REFERENCES ROLE (ID_Role);

ALTER TABLE ROLExENGINEER ADD
	CONSTRAINT FK_ENGINEER_ROLExENGINEER_ID_Engineer
	FOREIGN KEY (ID_Engineer)
	REFERENCES ENGINEER (ID_Engineer);

ALTER TABLE PROJECT ADD
	CONSTRAINT FK_PROJECT_ENGINEER_ID_Engineer
	FOREIGN KEY (ID_Engineer)
	REFERENCES ENGINEER (ID_Engineer);

ALTER TABLE PROJECT ADD
	CONSTRAINT FK_PROJECT_CUSTOMER_ID_Customer
	FOREIGN KEY (ID_Customer)
	REFERENCES CUSTOMER (ID_Customer);

ALTER TABLE PROJECT_STAGE ADD
	CONSTRAINT FK_PROJECT_STAGE_PROJECT_ID_Project
	FOREIGN KEY (ID_Project)
	REFERENCES PROJECT (ID_Project);

ALTER TABLE PROJECT_STAGE ADD
	CONSTRAINT FK_PROJECT_STAGE_STAGE_NAME_ID_Stage_Name
	FOREIGN KEY (ID_Stage_Name)
	REFERENCES STAGE_NAME (ID_Stage_Name);

ALTER TABLE PRODUCTxSTAGE ADD
	CONSTRAINT FK_PRODUCTxSTAGE_PROJECT_STAGE_ID_Stage
	FOREIGN KEY (ID_Stage)
	REFERENCES PROJECT_STAGE (ID_Stage);

ALTER TABLE PRODUCTxSTAGE ADD
	CONSTRAINT FK_PRODUCTxSTAGE_PRODUCT_ID_Product
	FOREIGN KEY (ID_Product)
	REFERENCES PRODUCT (ID_Product);