/*************** DELETE ALL DATABASE *********************/

DROP FUNCTION IF EXISTS add_customer(int,varchar(25),varchar(25),varchar(25),varchar(15),varchar(50),varchar(25),varchar(25));
DROP FUNCTION IF EXISTS add_product(text,text,text,text,text) CASCADE;

ALTER TABLE ROLExENGINEER DROP CONSTRAINT FK_ENGINEER_ROLExENGINEER_ID_Engineer;
ALTER TABLE ROLExENGINEER DROP CONSTRAINT fk_rolexengineer_role_id_role ;
ALTER TABLE PROJECT DROP CONSTRAINT FK_PROJECT_ENGINEER_ID_Engineer;
ALTER TABLE PROJECT DROP CONSTRAINT FK_PROJECT_CUSTOMER_ID_Customer;
ALTER TABLE PROJECT_STAGE DROP CONSTRAINT FK_PROJECT_STAGE_PROJECT_ID_Project;
ALTER TABLE PROJECT_STAGE DROP CONSTRAINT FK_PROJECT_STAGE_STAGE_NAME_ID_Stage_Name;
ALTER TABLE PRODUCTxSTAGE DROP CONSTRAINT FK_PRODUCTxSTAGE_PROJECT_STAGE_ID_Stage;
ALTER TABLE PRODUCTxSTAGE DROP CONSTRAINT FK_PRODUCTxSTAGE_PRODUCT_ID_Product;


DROP TABLE CUSTOMER CASCADE;
DROP TABLE ENGINEER;
DROP TABLE ROLE;
DROP TABLE ROLExENGINEER;
DROP TABLE PROJECT;
DROP TABLE PROJECT_STAGE CASCADE;
DROP TABLE STAGE_NAME;
DROP TABLE PRODUCTxSTAGE;
DROP TABLE PRODUCT CASCADE;
DROP SEQUENCE Role_seq;
DROP SEQUENCE ROLExENGINEER_seq;
DROP SEQUENCE PROJECT_seq;
DROP SEQUENCE PROJECT_STAGE_seq;
DROP SEQUENCE STAGE_NAME_seq;
DROP SEQUENCE PRODUCTxSTAGE_seq;
DROP SEQUENCE PRODUCT_seq;



/******************Create DATABASE ************************/

CREATE SEQUENCE Role_seq;
CREATE SEQUENCE ROLExENGINEER_seq;
CREATE SEQUENCE PROJECT_seq;
CREATE SEQUENCE PROJECT_STAGE_seq;
CREATE SEQUENCE STAGE_NAME_seq;
CREATE SEQUENCE PRODUCTxSTAGE_seq;
CREATE SEQUENCE PRODUCT_seq;

CREATE TABLE CUSTOMER(
	ID_Customer int PRIMARY KEY NOT NULL,
	Name varchar(25) NOT NULL,
	LastName1 varchar(25) NOT NULL,
	LastName2 varchar(25) NOT NULL,
	Phone varchar(15),
	Email varchar(50) NOT NULL,
	Username varchar(25) NOT NULL,
	Password varchar(25) NOT NULL,
	Active boolean NOT NULL
);

CREATE TABLE ENGINEER(
	ID_Engineer int PRIMARY KEY NOT NULL,
	Name varchar(25) NOT NULL,
	LastName1 varchar(25) NOT NULL,
	LastName2 varchar(25) NOT NULL,
	Phone varchar(15),
	Email varchar(50) NOT NULL,
	Eng_Code varchar(15) NOT NULL,
	Username varchar(25) NOT NULL,
	Password varchar(25) NOT NULL,
	Active boolean NOT NULL
);

CREATE TABLE ROLE(
	ID_Role int PRIMARY KEY NOT NULL DEFAULT nextval('Role_seq'),
	Name varchar(25) NOT NULL UNIQUE
);


CREATE TABLE ROLExENGINEER(
	ID_ROLExENGINEER int PRIMARY KEY NOT NULL DEFAULT nextval('ROLExENGINEER_seq'),
	ID_Engineer int NOT NULL,
	ID_Role int NOT NULL,
	UNIQUE(ID_Engineer,ID_Role)
);

CREATE TABLE PROJECT(
	ID_PROJECT int PRIMARY KEY NOT NULL DEFAULT nextval('PROJECT_seq'),
	Name varchar(50) NOT NULL UNIQUE,
	Location varchar(50) NOT NULL,
	ID_Engineer int NOT NULL,
	ID_Customer int NOT NULL,
	Comments varchar(255),
	Details varchar(255),
	Active boolean NOT NULL,
	Completed boolean NOT NULL
);

CREATE TABLE PROJECT_STAGE(
	ID_STAGE int PRIMARY KEY NOT NULL DEFAULT nextval('PROJECT_STAGE_seq'),
	ID_Stage_Name int NOT NULL,
	ID_Project int NOT NULL,
	Start_Date DATE,
	End_Date DATE,
	Details varchar(255),
	Completed boolean NOT NULL,
	Comments varchar(255),
	UNIQUE(ID_Stage_Name,ID_Project)
);

CREATE TABLE STAGE_NAME(
	ID_STAGE_NAME int PRIMARY KEY NOT NULL DEFAULT nextval('STAGE_NAME_seq'),
	Name varchar(255) UNIQUE
);

CREATE TABLE PRODUCTxSTAGE(
	ID_PRODUCTXSTAGE int PRIMARY KEY NOT NULL DEFAULT nextval('PRODUCTxSTAGE_seq'),
	ID_Product int NOT NULL,
	Quantity int,
	Price int,
	Purchased boolean NOT NULL,
	ID_Stage int NOT NULL,
	UNIQUE(ID_Product,ID_Stage)
);

CREATE TABLE PRODUCT(
	ID_Product int PRIMARY KEY NOT NULL DEFAULT nextval('PRODUCT_seq'),
	Details varchar(255),
	Active boolean NOT NULL,
	Name varchar(50) NOT NULL,
	Price int NOT NULL
);
