
/*INSERT INTO CUSTOMER VALUES(2014068784,'Fabian','Solano','Madriz','88833746','fasm2296@gmail.com','fasm22','123');
INSERT INTO CUSTOMER VALUES(2014033001,'Lenin','Torres','Valverde','85853232','ttvleninn@gmail.com','tvlenin','123');
INSERT INTO CUSTOMER VALUES(2014022421,'Abraham,','Arias','Chinchilla','88833746','abrahamon@gmail.com','abrahamon','123');
INSERT INTO CUSTOMER VALUES(2014078784,'David','Monestel','Madriz','88833746','david@gmail.com','david','123');*/

SELECT * FROM ENGINEER;

INSERT INTO ENGINEER VALUES(304980022,'Randall','ElChiqui','Brenes','85456323','randall@gmail.com','ACD459','chiqui08','123');
INSERT INTO ENGINEER VALUES(408830265,'Erick','ElChoque','Alvarado','86365645','erick@gmail.com','ADD325','choque07','123');

INSERT INTO ROLE VALUES('Ingeniero');
INSERT INTO ROLE VALUES('Arquitecto');

INSERT INTO ROLExENGINEER VALUES(304980022,1);
INSERT INTO ROLExENGINEER VALUES(408830265,2);

INSERT INTO STAGE_NAME VALUES('Cimientos');
INSERT INTO STAGE_NAME VALUES('Paredes');
INSERT INTO STAGE_NAME VALUES('Concreto Reforzado');
INSERT INTO STAGE_NAME VALUES('Techos');
INSERT INTO STAGE_NAME VALUES('Cielos');
INSERT INTO STAGE_NAME VALUES('Repello');
INSERT INTO STAGE_NAME VALUES('Entrepisos');
INSERT INTO STAGE_NAME VALUES('Pisos');
INSERT INTO STAGE_NAME VALUES('Enchapes');
INSERT INTO STAGE_NAME VALUES('Instalación Pluvial');
INSERT INTO STAGE_NAME VALUES('Instalación Sanitaria');
INSERT INTO STAGE_NAME VALUES('Instalación Eléctrica');
INSERT INTO STAGE_NAME VALUES('Puertas');
INSERT INTO STAGE_NAME VALUES(' Cerrajería');
INSERT INTO STAGE_NAME VALUES('Ventanas');
INSERT INTO STAGE_NAME VALUES('Closets');
INSERT INTO STAGE_NAME VALUES('Mueble de Cocina');
INSERT INTO STAGE_NAME VALUES('Escaleras');

INSERT INTO PRODUCT VALUES('Clavos de alta calidad',1,'Clavos',50);
INSERT INTO PRODUCT VALUES('Cemento',1,'Cemento',5000);
INSERT INTO PRODUCT VALUES('Lata de Zinc',1,'Zinc',3200);
INSERT INTO PRODUCT VALUES('Madera de calidad media',1,'Madera',3200);


INSERT INTO PROJECT VALUES('Casa de Fabian','Paraiso',304980022,2014068784,'','');

INSERT INTO PROJECT_STAGE VALUES(1,1,'5/5/2020','10/5/2020','Etapa inicial',0,'');

