
INSERT INTO CUSTOMER VALUES(2014068784,'Fabian','Solano','Madriz','88833746','fasm2296@gmail.com','fasm22','123',True);
INSERT INTO CUSTOMER VALUES(2014033001,'Lenin','Torres','Valverde','85853232','ttvleninn@gmail.com','tvlenin','123',True);
INSERT INTO CUSTOMER VALUES(2014022421,'Abraham,','Arias','Chinchilla','88833746','abrahamon@gmail.com','abrahamon','123',True);
INSERT INTO CUSTOMER VALUES(2014078784,'David','Monestel','Madriz','88833746','david@gmail.com','david','123',True);


INSERT INTO ENGINEER VALUES(304980022,'Randall','ElChiqui','Brenes','85456323','randall@gmail.com','ACD459','chiqui08','123',True);
INSERT INTO ENGINEER VALUES(408830265,'Erick','ElChoque','Alvarado','86365645','erick@gmail.com','ADD325','choque07','123',True);


INSERT INTO ROLE VALUES(DEFAULT,'Ingeniero');
INSERT INTO ROLE VALUES(DEFAULT,'Arquitecto');

INSERT INTO ROLExENGINEER VALUES(DEFAULT,304980022,1);
INSERT INTO ROLExENGINEER VALUES(DEFAULT,408830265,2);

INSERT INTO STAGE_NAME VALUES(DEFAULT,'Cimientos');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Paredes');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Concreto Reforzado');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Techos');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Cielos');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Repello');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Entrepisos');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Pisos');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Enchapes');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Instalación Pluvial');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Instalación Sanitaria');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Instalación Eléctrica');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Puertas');
INSERT INTO STAGE_NAME VALUES(DEFAULT,' Cerrajería');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Ventanas');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Closets');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Mueble de Cocina');
INSERT INTO STAGE_NAME VALUES(DEFAULT,'Escaleras');

INSERT INTO PRODUCT VALUES(DEFAULT,'Clavos de alta calidad',True,'Clavos',50);
INSERT INTO PRODUCT VALUES(DEFAULT,'Cemento',True,'Cemento',5000);
INSERT INTO PRODUCT VALUES(DEFAULT,'Lata de Zinc',True,'Zinc',3200);
INSERT INTO PRODUCT VALUES(DEFAULT,'Madera de calidad media',True,'Madera',3200);


INSERT INTO PROJECT VALUES(DEFAULT,'Casa de Fabian','Paraiso',304980022,2014068784,'','',True);

INSERT INTO PROJECT_STAGE VALUES(DEFAULT,1,1,'5/5/2020','10/5/2020','Etapa inicial',False,'');


--SELECT STAGE_NAME.Name FROM STAGE_NAME,PROJECT_STAGE WHERE PROJECT_STAGE.ID_STAGE=STAGE_NAME.ID_Stage_Name;
--SELECT * FROM ENGINEER right JOIN PROJECT ON PROJECT.ID_Engineer=ENGINEER.ID_Engineer;


--SELECT ENGINEER.Name FROM ENGINEER,PROJECT WHERE PROJECT.ID_Engineer=ENGINEER.ID_Engineer;
