//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRESTService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Secure_PassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BDate {
            get {
                return this.BDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BDateField, value) != true)) {
                    this.BDateField = value;
                    this.RaisePropertyChanged("BDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Card {
            get {
                return this.ID_CardField;
            }
            set {
                if ((this.ID_CardField.Equals(value) != true)) {
                    this.ID_CardField = value;
                    this.RaisePropertyChanged("ID_Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PriorityLevel {
            get {
                return this.PriorityLevelField;
            }
            set {
                if ((this.PriorityLevelField.Equals(value) != true)) {
                    this.PriorityLevelField = value;
                    this.RaisePropertyChanged("PriorityLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Residence {
            get {
                return this.ResidenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenceField, value) != true)) {
                    this.ResidenceField = value;
                    this.RaisePropertyChanged("Residence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secure_Pass {
            get {
                return this.Secure_PassField;
            }
            set {
                if ((object.ReferenceEquals(this.Secure_PassField, value) != true)) {
                    this.Secure_PassField = value;
                    this.RaisePropertyChanged("Secure_Pass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BOfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_SupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TaxFreeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BOffice {
            get {
                return this.BOfficeField;
            }
            set {
                if ((this.BOfficeField.Equals(value) != true)) {
                    this.BOfficeField = value;
                    this.RaisePropertyChanged("BOffice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Category {
            get {
                return this.ID_CategoryField;
            }
            set {
                if ((this.ID_CategoryField.Equals(value) != true)) {
                    this.ID_CategoryField = value;
                    this.RaisePropertyChanged("ID_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Product {
            get {
                return this.ID_ProductField;
            }
            set {
                if ((this.ID_ProductField.Equals(value) != true)) {
                    this.ID_ProductField = value;
                    this.RaisePropertyChanged("ID_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Supplier {
            get {
                return this.ID_SupplierField;
            }
            set {
                if ((this.ID_SupplierField.Equals(value) != true)) {
                    this.ID_SupplierField = value;
                    this.RaisePropertyChanged("ID_Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TaxFree {
            get {
                return this.TaxFreeField;
            }
            set {
                if ((this.TaxFreeField.Equals(value) != true)) {
                    this.TaxFreeField = value;
                    this.RaisePropertyChanged("TaxFree");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order_Check", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Order_Check : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BOfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Customer_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Date_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Order_StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BOffice {
            get {
                return this.BOfficeField;
            }
            set {
                if ((this.BOfficeField.Equals(value) != true)) {
                    this.BOfficeField = value;
                    this.RaisePropertyChanged("BOffice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_ID {
            get {
                return this.Customer_IDField;
            }
            set {
                if ((this.Customer_IDField.Equals(value) != true)) {
                    this.Customer_IDField = value;
                    this.RaisePropertyChanged("Customer_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_Time {
            get {
                return this.Date_TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.Date_TimeField, value) != true)) {
                    this.Date_TimeField = value;
                    this.RaisePropertyChanged("Date_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Order_Status {
            get {
                return this.Order_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_StatusField, value) != true)) {
                    this.Order_StatusField = value;
                    this.RaisePropertyChanged("Order_Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Category {
            get {
                return this.ID_CategoryField;
            }
            set {
                if ((this.ID_CategoryField.Equals(value) != true)) {
                    this.ID_CategoryField = value;
                    this.RaisePropertyChanged("ID_Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginAuth", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class LoginAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Secure_PassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secure_Pass {
            get {
                return this.Secure_PassField;
            }
            set {
                if ((object.ReferenceEquals(this.Secure_PassField, value) != true)) {
                    this.Secure_PassField = value;
                    this.RaisePropertyChanged("Secure_Pass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginEmployee", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class LoginEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Secure_PassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secure_Pass {
            get {
                return this.Secure_PassField;
            }
            set {
                if ((object.ReferenceEquals(this.Secure_PassField, value) != true)) {
                    this.Secure_PassField = value;
                    this.RaisePropertyChanged("Secure_Pass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BOffice_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Secure_PassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BDate {
            get {
                return this.BDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BDateField, value) != true)) {
                    this.BDateField = value;
                    this.RaisePropertyChanged("BDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BOffice_ID {
            get {
                return this.BOffice_IDField;
            }
            set {
                if ((this.BOffice_IDField.Equals(value) != true)) {
                    this.BOffice_IDField = value;
                    this.RaisePropertyChanged("BOffice_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Employee {
            get {
                return this.ID_EmployeeField;
            }
            set {
                if ((this.ID_EmployeeField.Equals(value) != true)) {
                    this.ID_EmployeeField = value;
                    this.RaisePropertyChanged("ID_Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Residence {
            get {
                return this.ResidenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenceField, value) != true)) {
                    this.ResidenceField = value;
                    this.RaisePropertyChanged("Residence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secure_Pass {
            get {
                return this.Secure_PassField;
            }
            set {
                if ((object.ReferenceEquals(this.Secure_PassField, value) != true)) {
                    this.Secure_PassField = value;
                    this.RaisePropertyChanged("Secure_Pass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purchase_Item", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Purchase_Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_ID {
            get {
                return this.Invoice_IDField;
            }
            set {
                if ((this.Invoice_IDField.Equals(value) != true)) {
                    this.Invoice_IDField = value;
                    this.RaisePropertyChanged("Invoice_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((this.Product_IDField.Equals(value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Supplier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_SupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Supplier {
            get {
                return this.ID_SupplierField;
            }
            set {
                if ((this.ID_SupplierField.Equals(value) != true)) {
                    this.ID_SupplierField = value;
                    this.RaisePropertyChanged("ID_Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericQuery", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class GenericQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataGField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataG {
            get {
                return this.DataGField;
            }
            set {
                if ((object.ReferenceEquals(this.DataGField, value) != true)) {
                    this.DataGField = value;
                    this.RaisePropertyChanged("DataG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Customer", ReplyAction="http://tempuri.org/IService1/Get_CustomerResponse")]
        string Get_Customer(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Customer", ReplyAction="http://tempuri.org/IService1/Get_CustomerResponse")]
        System.Threading.Tasks.Task<string> Get_CustomerAsync(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCustomer", ReplyAction="http://tempuri.org/IService1/PostCustomerResponse")]
        string PostCustomer(MyRESTService.ServiceReference1.Customer str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCustomer", ReplyAction="http://tempuri.org/IService1/PostCustomerResponse")]
        System.Threading.Tasks.Task<string> PostCustomerAsync(MyRESTService.ServiceReference1.Customer str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        string UpdateCustomer(MyRESTService.ServiceReference1.Customer str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<string> UpdateCustomerAsync(MyRESTService.ServiceReference1.Customer str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUpdateProduct", ReplyAction="http://tempuri.org/IService1/PostUpdateProductResponse")]
        string PostUpdateProduct(MyRESTService.ServiceReference1.Product str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUpdateProduct", ReplyAction="http://tempuri.org/IService1/PostUpdateProductResponse")]
        System.Threading.Tasks.Task<string> PostUpdateProductAsync(MyRESTService.ServiceReference1.Product str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        string DeleteCustomer(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<string> DeleteCustomerAsync(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrder", ReplyAction="http://tempuri.org/IService1/UpdateOrderResponse")]
        string UpdateOrder(string id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrder", ReplyAction="http://tempuri.org/IService1/UpdateOrderResponse")]
        System.Threading.Tasks.Task<string> UpdateOrderAsync(string id, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSupplier", ReplyAction="http://tempuri.org/IService1/DeleteSupplierResponse")]
        string DeleteSupplier(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSupplier", ReplyAction="http://tempuri.org/IService1/DeleteSupplierResponse")]
        System.Threading.Tasks.Task<string> DeleteSupplierAsync(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        string GetOrders(string suc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        System.Threading.Tasks.Task<string> GetOrdersAsync(string suc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostOrder", ReplyAction="http://tempuri.org/IService1/PostOrderResponse")]
        string PostOrder(MyRESTService.ServiceReference1.Order_Check str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostOrder", ReplyAction="http://tempuri.org/IService1/PostOrderResponse")]
        System.Threading.Tasks.Task<string> PostOrderAsync(MyRESTService.ServiceReference1.Order_Check str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCategory", ReplyAction="http://tempuri.org/IService1/PostCategoryResponse")]
        string PostCategory(MyRESTService.ServiceReference1.Category str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCategory", ReplyAction="http://tempuri.org/IService1/PostCategoryResponse")]
        System.Threading.Tasks.Task<string> PostCategoryAsync(MyRESTService.ServiceReference1.Category str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostLogin", ReplyAction="http://tempuri.org/IService1/PostLoginResponse")]
        string PostLogin(MyRESTService.ServiceReference1.LoginAuth str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostLogin", ReplyAction="http://tempuri.org/IService1/PostLoginResponse")]
        System.Threading.Tasks.Task<string> PostLoginAsync(MyRESTService.ServiceReference1.LoginAuth str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostLoginEmployee", ReplyAction="http://tempuri.org/IService1/PostLoginEmployeeResponse")]
        string PostLoginEmployee(MyRESTService.ServiceReference1.LoginEmployee str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostLoginEmployee", ReplyAction="http://tempuri.org/IService1/PostLoginEmployeeResponse")]
        System.Threading.Tasks.Task<string> PostLoginEmployeeAsync(MyRESTService.ServiceReference1.LoginEmployee str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostEmployee", ReplyAction="http://tempuri.org/IService1/PostEmployeeResponse")]
        string PostEmployee(MyRESTService.ServiceReference1.Employee str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostEmployee", ReplyAction="http://tempuri.org/IService1/PostEmployeeResponse")]
        System.Threading.Tasks.Task<string> PostEmployeeAsync(MyRESTService.ServiceReference1.Employee str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        string GetProducts(string paramList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Threading.Tasks.Task<string> GetProductsAsync(string paramList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostProduct", ReplyAction="http://tempuri.org/IService1/PostProductResponse")]
        string PostProduct(MyRESTService.ServiceReference1.Product str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostProduct", ReplyAction="http://tempuri.org/IService1/PostProductResponse")]
        System.Threading.Tasks.Task<string> PostProductAsync(MyRESTService.ServiceReference1.Product str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Post_Purchase_Item", ReplyAction="http://tempuri.org/IService1/Post_Purchase_ItemResponse")]
        string Post_Purchase_Item(MyRESTService.ServiceReference1.Purchase_Item str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Post_Purchase_Item", ReplyAction="http://tempuri.org/IService1/Post_Purchase_ItemResponse")]
        System.Threading.Tasks.Task<string> Post_Purchase_ItemAsync(MyRESTService.ServiceReference1.Purchase_Item str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Post_Supplier", ReplyAction="http://tempuri.org/IService1/Post_SupplierResponse")]
        string Post_Supplier(MyRESTService.ServiceReference1.Supplier str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Post_Supplier", ReplyAction="http://tempuri.org/IService1/Post_SupplierResponse")]
        System.Threading.Tasks.Task<string> Post_SupplierAsync(MyRESTService.ServiceReference1.Supplier str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Post_Shop", ReplyAction="http://tempuri.org/IService1/Post_ShopResponse")]
        string Post_Shop(MyRESTService.ServiceReference1.GenericQuery str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Post_Shop", ReplyAction="http://tempuri.org/IService1/Post_ShopResponse")]
        System.Threading.Tasks.Task<string> Post_ShopAsync(MyRESTService.ServiceReference1.GenericQuery str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Order", ReplyAction="http://tempuri.org/IService1/Get_OrderResponse")]
        string Get_Order(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Order", ReplyAction="http://tempuri.org/IService1/Get_OrderResponse")]
        System.Threading.Tasks.Task<string> Get_OrderAsync(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Stadistics", ReplyAction="http://tempuri.org/IService1/Get_StadisticsResponse")]
        string Get_Stadistics(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_Stadistics", ReplyAction="http://tempuri.org/IService1/Get_StadisticsResponse")]
        System.Threading.Tasks.Task<string> Get_StadisticsAsync(string msj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBoffice", ReplyAction="http://tempuri.org/IService1/GetBofficeResponse")]
        string GetBoffice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBoffice", ReplyAction="http://tempuri.org/IService1/GetBofficeResponse")]
        System.Threading.Tasks.Task<string> GetBofficeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        string DeleteProduct(string idP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task<string> DeleteProductAsync(string idP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSupplier", ReplyAction="http://tempuri.org/IService1/GetSupplierResponse")]
        string GetSupplier();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSupplier", ReplyAction="http://tempuri.org/IService1/GetSupplierResponse")]
        System.Threading.Tasks.Task<string> GetSupplierAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBoffice", ReplyAction="http://tempuri.org/IService1/PostBofficeResponse")]
        string PostBoffice(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBoffice", ReplyAction="http://tempuri.org/IService1/PostBofficeResponse")]
        System.Threading.Tasks.Task<string> PostBofficeAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MyRESTService.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MyRESTService.ServiceReference1.IService1>, MyRESTService.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get_Customer(string msj) {
            return base.Channel.Get_Customer(msj);
        }
        
        public System.Threading.Tasks.Task<string> Get_CustomerAsync(string msj) {
            return base.Channel.Get_CustomerAsync(msj);
        }
        
        public string PostCustomer(MyRESTService.ServiceReference1.Customer str) {
            return base.Channel.PostCustomer(str);
        }
        
        public System.Threading.Tasks.Task<string> PostCustomerAsync(MyRESTService.ServiceReference1.Customer str) {
            return base.Channel.PostCustomerAsync(str);
        }
        
        public string UpdateCustomer(MyRESTService.ServiceReference1.Customer str) {
            return base.Channel.UpdateCustomer(str);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCustomerAsync(MyRESTService.ServiceReference1.Customer str) {
            return base.Channel.UpdateCustomerAsync(str);
        }
        
        public string PostUpdateProduct(MyRESTService.ServiceReference1.Product str) {
            return base.Channel.PostUpdateProduct(str);
        }
        
        public System.Threading.Tasks.Task<string> PostUpdateProductAsync(MyRESTService.ServiceReference1.Product str) {
            return base.Channel.PostUpdateProductAsync(str);
        }
        
        public string DeleteCustomer(string msj) {
            return base.Channel.DeleteCustomer(msj);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCustomerAsync(string msj) {
            return base.Channel.DeleteCustomerAsync(msj);
        }
        
        public string UpdateOrder(string id, string status) {
            return base.Channel.UpdateOrder(id, status);
        }
        
        public System.Threading.Tasks.Task<string> UpdateOrderAsync(string id, string status) {
            return base.Channel.UpdateOrderAsync(id, status);
        }
        
        public string DeleteSupplier(string msj) {
            return base.Channel.DeleteSupplier(msj);
        }
        
        public System.Threading.Tasks.Task<string> DeleteSupplierAsync(string msj) {
            return base.Channel.DeleteSupplierAsync(msj);
        }
        
        public string GetOrders(string suc) {
            return base.Channel.GetOrders(suc);
        }
        
        public System.Threading.Tasks.Task<string> GetOrdersAsync(string suc) {
            return base.Channel.GetOrdersAsync(suc);
        }
        
        public string PostOrder(MyRESTService.ServiceReference1.Order_Check str) {
            return base.Channel.PostOrder(str);
        }
        
        public System.Threading.Tasks.Task<string> PostOrderAsync(MyRESTService.ServiceReference1.Order_Check str) {
            return base.Channel.PostOrderAsync(str);
        }
        
        public string PostCategory(MyRESTService.ServiceReference1.Category str) {
            return base.Channel.PostCategory(str);
        }
        
        public System.Threading.Tasks.Task<string> PostCategoryAsync(MyRESTService.ServiceReference1.Category str) {
            return base.Channel.PostCategoryAsync(str);
        }
        
        public string PostLogin(MyRESTService.ServiceReference1.LoginAuth str) {
            return base.Channel.PostLogin(str);
        }
        
        public System.Threading.Tasks.Task<string> PostLoginAsync(MyRESTService.ServiceReference1.LoginAuth str) {
            return base.Channel.PostLoginAsync(str);
        }
        
        public string PostLoginEmployee(MyRESTService.ServiceReference1.LoginEmployee str) {
            return base.Channel.PostLoginEmployee(str);
        }
        
        public System.Threading.Tasks.Task<string> PostLoginEmployeeAsync(MyRESTService.ServiceReference1.LoginEmployee str) {
            return base.Channel.PostLoginEmployeeAsync(str);
        }
        
        public string PostEmployee(MyRESTService.ServiceReference1.Employee str) {
            return base.Channel.PostEmployee(str);
        }
        
        public System.Threading.Tasks.Task<string> PostEmployeeAsync(MyRESTService.ServiceReference1.Employee str) {
            return base.Channel.PostEmployeeAsync(str);
        }
        
        public string GetProducts(string paramList) {
            return base.Channel.GetProducts(paramList);
        }
        
        public System.Threading.Tasks.Task<string> GetProductsAsync(string paramList) {
            return base.Channel.GetProductsAsync(paramList);
        }
        
        public string PostProduct(MyRESTService.ServiceReference1.Product str) {
            return base.Channel.PostProduct(str);
        }
        
        public System.Threading.Tasks.Task<string> PostProductAsync(MyRESTService.ServiceReference1.Product str) {
            return base.Channel.PostProductAsync(str);
        }
        
        public string Post_Purchase_Item(MyRESTService.ServiceReference1.Purchase_Item str) {
            return base.Channel.Post_Purchase_Item(str);
        }
        
        public System.Threading.Tasks.Task<string> Post_Purchase_ItemAsync(MyRESTService.ServiceReference1.Purchase_Item str) {
            return base.Channel.Post_Purchase_ItemAsync(str);
        }
        
        public string Post_Supplier(MyRESTService.ServiceReference1.Supplier str) {
            return base.Channel.Post_Supplier(str);
        }
        
        public System.Threading.Tasks.Task<string> Post_SupplierAsync(MyRESTService.ServiceReference1.Supplier str) {
            return base.Channel.Post_SupplierAsync(str);
        }
        
        public string Post_Shop(MyRESTService.ServiceReference1.GenericQuery str) {
            return base.Channel.Post_Shop(str);
        }
        
        public System.Threading.Tasks.Task<string> Post_ShopAsync(MyRESTService.ServiceReference1.GenericQuery str) {
            return base.Channel.Post_ShopAsync(str);
        }
        
        public string Get_Order(string msj) {
            return base.Channel.Get_Order(msj);
        }
        
        public System.Threading.Tasks.Task<string> Get_OrderAsync(string msj) {
            return base.Channel.Get_OrderAsync(msj);
        }
        
        public string Get_Stadistics(string msj) {
            return base.Channel.Get_Stadistics(msj);
        }
        
        public System.Threading.Tasks.Task<string> Get_StadisticsAsync(string msj) {
            return base.Channel.Get_StadisticsAsync(msj);
        }
        
        public string GetBoffice() {
            return base.Channel.GetBoffice();
        }
        
        public System.Threading.Tasks.Task<string> GetBofficeAsync() {
            return base.Channel.GetBofficeAsync();
        }
        
        public string DeleteProduct(string idP) {
            return base.Channel.DeleteProduct(idP);
        }
        
        public System.Threading.Tasks.Task<string> DeleteProductAsync(string idP) {
            return base.Channel.DeleteProductAsync(idP);
        }
        
        public string GetSupplier() {
            return base.Channel.GetSupplier();
        }
        
        public System.Threading.Tasks.Task<string> GetSupplierAsync() {
            return base.Channel.GetSupplierAsync();
        }
        
        public string PostBoffice(string Name) {
            return base.Channel.PostBoffice(Name);
        }
        
        public System.Threading.Tasks.Task<string> PostBofficeAsync(string Name) {
            return base.Channel.PostBofficeAsync(Name);
        }
    }
}
